#!/usr/bin/env bash
#
# Build mistlib-wasm from source and vendor the release artifacts.
#
# Clones the mistlib source repo (set via MISTLIB_REPO), runs the official
# release build (`wasm-pack build --target web --release`) and copies the
# generated pkg/ files into src/vendor/mistlib-wasm/ where the app imports them.
#
# Requirements: git, rustup (with the wasm32-unknown-unknown target) and
# wasm-pack. Missing pieces are installed automatically when possible.
#
# The source repository URL is intentionally NOT hardcoded — it is a private
# repo and this file may live in a public repository. Set MISTLIB_REPO before
# running, e.g.:
#
#   MISTLIB_REPO=git@github.com:<org>/<repo>.git scripts/build-mistlib.sh
#   MISTLIB_REPO=... MISTLIB_REF=some-branch scripts/build-mistlib.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load MISTLIB_* (and anything else) from .env if present, without clobbering
# values already set in the environment. .env is gitignored, so the private
# repo URL stays out of version control.
if [ -f "$ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "$ROOT/.env"
  set +a
fi

REPO="${MISTLIB_REPO:?set MISTLIB_REPO to the mistlib source repository URL (not hardcoded; private repo)}"
REF="${MISTLIB_REF:-enhance/peer-connection}"
SUBDIR="${MISTLIB_SUBDIR:-mistlib-wasm}"

VENDOR="$ROOT/src/vendor/mistlib-wasm"

export PATH="$HOME/.cargo/bin:$PATH"

echo ">> mistlib-wasm vendor build"
echo "   repo:   $REPO"
echo "   ref:    $REF"
echo "   subdir: $SUBDIR"

# --- toolchain -------------------------------------------------------------
command -v cargo >/dev/null 2>&1 || { echo "error: cargo (rust toolchain) is required" >&2; exit 1; }

if command -v rustup >/dev/null 2>&1; then
  rustup target add wasm32-unknown-unknown >/dev/null 2>&1 || true
fi

if ! command -v wasm-pack >/dev/null 2>&1; then
  echo ">> installing wasm-pack..."
  cargo install wasm-pack
fi

# --- clone -----------------------------------------------------------------
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
echo ">> cloning $REF ..."
git clone --depth 1 -b "$REF" "$REPO" "$WORK/src"

# --- build -----------------------------------------------------------------
echo ">> building (release, target web) ..."
# Strip local filesystem paths (which include the username) from panic/debug
# strings embedded in the wasm, since the artifacts are committed publicly.
REMAP="--remap-path-prefix=$HOME=~ --remap-path-prefix=$WORK/src=src"
( cd "$WORK/src/$SUBDIR" && RUSTFLAGS="${RUSTFLAGS:+$RUSTFLAGS }$REMAP" wasm-pack build --target web --release )

PKG="$WORK/src/$SUBDIR/pkg"
[ -f "$PKG/mistlib_wasm.js" ] || { echo "error: build did not produce pkg/mistlib_wasm.js" >&2; exit 1; }

# --- vendor ----------------------------------------------------------------
echo ">> copying artifacts into $VENDOR ..."
mkdir -p "$VENDOR"
for f in mistlib_wasm.js mistlib_wasm.d.ts mistlib_wasm_bg.wasm mistlib_wasm_bg.wasm.d.ts; do
  cp "$PKG/$f" "$VENDOR/$f"
done

# Record provenance so it's clear which commit produced these artifacts.
COMMIT="$(git -C "$WORK/src" rev-parse HEAD)"
# Note: the source repo URL is deliberately omitted here so it does not get
# committed (private repo / possibly public vendor location).
cat > "$VENDOR/BUILD_INFO.txt" <<EOF
Generated by scripts/build-mistlib.sh — do not edit by hand.
ref:    $REF
commit: $COMMIT
built:  $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo ">> done. Vendored mistlib-wasm @ $COMMIT"
